### PR TITLE
Remove logging functionality and drop bunyan dependency.

### LINKED ISSUE #37: Build errors (node-gyp) stemming from bunyan/dtrace-provider deps
Is anyone else getting node-gyp errors related from the Bunyan dependency? I've read through various issues in the Bunyan and dtrace-provider repositories, but haven't found a concrete way around this that doesn't involve:

A) Installing python
B) Installing the windows essentials package
C) Manually editing the package-lock

Mainly just curious if anyone else is seeing this and if they have found a good workaround or if there is something we could change in the package.json to resolve the issue for everyone.

### PR DESCRIPTION
**Pull request by AndrewSouthpaw**
Closes #37. 

~Generally seems like bunyan has trouble building on people's machines for reasons that I cannot understand, but given the minor role the logger plays it seems overkill to bring in such a fully-featured logger.~

~I subbed it out with [`diary`](https://github.com/maraisr/diary), which is super fast, tiny, and does the trick. It creates a scoped logger, which is silent by default, unless you choose to listen to it:~

```
const { enable } = require('diary')

enable('*') // allow everything
enable('jest-when: my-logger') // allow a specific logger
```

~If we wanted to move forward with these changes, it'd be worth mentioning the functionality in the README.~

But honestly, I think it'd be better to drop the logger entirely. It's not a feature people know about, and I'm not convinced it's worth keeping a logger around anyway. It just adds another dependency, and I'm not sure anyone would use it.

If @timkindberg agrees, I can completely pull out the logger code so this library stays as slim as possible.

[EDIT]

Based off discussion, changing this PR to fully remove logging functionality and dependencies.

### CODE REVIEW

**Comment by timkindberg** [comment]
Let's just remove it

**Comment by AndrewSouthpaw** [comment]
Updated!

**Comment by AndrewSouthpaw** [comment]
Thanks for accepting my PR! This is a great library, and does exactly what I needed. 😄

**Comment by timkindberg** [comment]
Hey thanks for the kind words and the contribution!

**Pull request merged**
