### PR TITLE
Fix non-chained default implementations (fixes #57)

### LINKED ISSUE #57: Using a default value does not update the whenified implementation
Sample code:

```
const { when } = require('jest-when')

it('allows defining the default when NOT chaining', () => {
  const fn = jest.fn()

  when(fn).mockRejectedValue(false)

  when(fn)
    .calledWith(expect.anything())
    .mockResolvedValue(true)

  expect(fn()).rejects.toEqual(false)
});
```

Expectation: The test case to pass

### PR DESCRIPTION
**Pull request by devzeebo**

### CODE REVIEW

**Comment by timkindberg** [comment]
Does this also fix #24 ?

**Comment by timkindberg** [comment]
Thanks BTW :)

**Comment by timkindberg** [comment]
jest-when@3.1.0

**Comment by devzeebo** [comment]
Unfortunately it doesn't fix #24, since the mock implementation isn't overridden until line 62. You'd have to declare the mock implementation in the constructor in order to enable it to be overridden with only a default implementation

**Pull request merged**
