### PR TITLE
feat(): make jest an peer dependancy

### PR DESCRIPTION
**Pull request by chyzwar**
This address #81. I tested with jest 24, 25, 26 and 27, it should work with other versions as well. This could be released as non-breaking change. My concern is that his still imports jesmineUtils from private module api see https://github.com/facebook/jest/blob/d6e5ddb0c3c1af54f443f225aa14cdf07c7bb593/packages/expect/package.json#L12

I think we should raise issue on jest repo to expose equals in public API of expect package.

### CODE REVIEW

**Comment by timkindberg** [comment]
Ok so even with the separate concern of importing equals from jasmineUtils you think this is safe to merge as a non-breaking minor release?

**Comment by chyzwar** [comment]
Yes, In my opinion it should safe but can run this patch tomorrow on large codebase at work. We use jest-when in few hundred tests.

**Comment by chyzwar** [comment]
I run on one of our codebases, it has 97 imports of jest-when, all tests passed and possibly slightly faster.

**Comment by ericcornelissen** [comment]
It's a minor data point but I run the tests for [ericcornelissen/svgo-action](https://github.com/ericcornelissen/svgo-action) successfully when using these changes.

**Pull request merged**
